server:
    port: 8081
    servlet:
      context-path: /product

spring:
  application:
    name: product
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/HQT
